/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPrintixTokenRouteImport } from './routes/api/printix-token'

const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrintixTokenRoute = ApiPrintixTokenRouteImport.update({
  id: '/api/printix-token',
  path: '/api/printix-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/api/printix-token': typeof ApiPrintixTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/api/printix-token': typeof ApiPrintixTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/api/printix-token': typeof ApiPrintixTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/openapi.json' | '/api/printix-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/openapi.json' | '/api/printix-token'
  id: '__root__' | '/' | '/openapi.json' | '/api/printix-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  ApiPrintixTokenRoute: typeof ApiPrintixTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/printix-token': {
      id: '/api/printix-token'
      path: '/api/printix-token'
      fullPath: '/api/printix-token'
      preLoaderRoute: typeof ApiPrintixTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  ApiPrintixTokenRoute: ApiPrintixTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
